### ISSUE TITLE
Unwanted horizontal scrollbar

### ISSUE THREAD

**Issue by hudochenkov** [molefrog/molefrog.com#32]
There is an unwanted horizontal scrollbar on https://molefrog.com/notes/react-tricks It is present on all window sizes.

![CleanShot 2023-12-20 at 00 22 16](https://github.com/molefrog/molefrog.com/assets/654597/d1a3ff01-e139-43d9-a689-543656c9a384)

P. S. Thank you for sharing your experience.

**Comment by molefrog** [comment]
@hudochenkov Thanks! I couldn't use `overflow: none` there because it is rendered by external library (react-notion-x), so I just introduced some padding instead. I'm not really proud with this fix, but I think it is good enough.

https://sbx.webflow.io/100vw-scrollbars
https://github.com/molefrog/molefrog.com/commit/460252e8786d0501201c2b746153b73d6cacefbe
